---
- name: use facts module
  hosts: cisco
  gather_facts: false

  tasks:
    - name: retrieve facts
      cisco.ios.ios_facts:

    - name: display version
      debug:
        msg: "{{ ansible_net_version }}"

    - name: display serial number
      debug:
        msg: "{{ ansible_net_serialnum }}"
