---
- name: add vlans
  hosts: arista
  gather_facts: false
  vars:
    vlans:
      - name: desktops
        vlan_id: 20
      - name: servers
        vlan_id: 30
      - name: DMZ
        vlan_id: 50

  tasks:
    - name: add VLAN configuration
      arista.eos.eos_vlans:
        state: merged
        config: "{{ vlans }}"
